#!/bin/bash -xe

# this runs on docker cloud as part of automated build, where IMAGE_NAME is set
# for you. For local runs, initialize using vars from ops/deploy.sh, which
# would've invoked this.
IMAGE_NAME=${IMAGE_NAME:=${REPO}/${DEPLOYPREFIX}}
DOCKER_REPO=${DOCKER_REPO:=${REPO}/${DEPLOYPREFIX}}
DEPLOYPREFIX=${DEPLOYPREFIX:=$(basename "${DOCKER_REPO}")}
# read the tags file from the image subdir
TAGS=$(< ${DEPLOYPREFIX}/tags)
docker build -t ${DOCKER_REPO}:${TAGS//,/ -t ${DOCKER_REPO}:} -f ${DOCKERFILE_PATH} .
